### ISSUE TITLE
不支持borderRadius样式！

### ISSUE THREAD

**Issue by DBshaoYan** [react-native-component/react-native-smart-image-loader#2]
我使用外层套<View> 设置 overflow: 'hidden' 化解了。请问下后面会支持圆角吗？

**Comment by cyqresig** [comment]
您好，
目前不会考虑对封装的ImageView增加native圆角实现，
如您希望实现圆角图片，可以参照web端的做法，在外面套一层父View, 并设置圆角边框和子View超出部分不显示即可。
